Auth / Social login & register
whaleap/during-budget pull request #364
Opened 2023-05-16 14:26 UTC by jessie129j

- Related: #358

2023-05-16 14:29 UTC, jessie129j commented
@navynj 358-social 브랜치의 이 커밋(https://github.com/whaleap/during-budget/pull/364/commits/498d8de860ca312519cb450e3cab8b6e0eff840f) 에서 클라이언트 코드 추가했습니다!

2023-05-17 01:59 UTC, jessie129j commented
@navynj 화면 사진도 첨부합니다!
1. `screens>components>Auth>EmailForm.tsx`
    <img src="https://github.com/whaleap/during-budget/assets/19641212/e5f64438-ca3a-45ea-a834-dbae5584f967" width="200" >
2. `screens>User.tsx`
    <img src="https://github.com/whaleap/during-budget/assets/19641212/a667976c-3732-4317-b142-a0cfd61aea74" width="200" >
3. `screens>Redirect.tsx`
    <img src="https://github.com/whaleap/during-budget/assets/19641212/58d22967-04a9-4efd-84d3-677b857bcbb6" width="200" >

2023-05-17 03:49 UTC, navynj requested changes
<img width="325" alt="image" src="https://github.com/whaleap/during-budget/assets/82319291/54d20fb4-74eb-48f5-81c9-ea54cda740f5">

- 기존 원형 아이콘 디자인으로 변형 (svg)
- 이메일 로그인 폼과 분리
- SNS 로그인/회원가입 모두 '시작하기'로 통일

2023-05-17 03:50 UTC, navynj approved these changes

2023-05-17 04:07 UTC, merged